jurimetria/urls.py
from django.urls import path

from . import views


app_name = "jurimetria"
urlpatterns = [
    path("", views.index, name="index"),
    path("resultado/", views.result, name="result"),
    path("<int:sentenca_id>/", views.detail, name="detail"),
]

jurimetria/models.py
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import models


class Sentenca(models.Model):
    tribunal = models.CharField(max_length=50)
    vara = models.CharField(max_length=50)
    numero = models.CharField(max_length=30)
    texto = models.TextField()
    decoded = models.TextField()
    tipo = models.CharField(max_length=20)
    pub_date = models.DateTimeField("data publicacao", null=True, blank=True)
    search_vector = SearchVectorField(null=True)

    def __str__(self):
        return self.numero

    class Meta:
        indexes = [GinIndex(fields=["search_vector"], name="jurimetria_search_vector_idx")]

jurimetria/views.py
from django.contrib.postgres.search import SearchQuery, SearchRank
from django.db.models import Count, F
from django.shortcuts import get_object_or_404, redirect, render

from unidecode import unidecode

from .models import Sentenca
from .rol_varas import VARAS_NOMES
from .util import coloca_acento, formata_numero_cnj, get_post_query_input, make_output_tuple, query_counts


def index(request):
    if request.method == "GET":
        return render(request, "jurimetria/index.html")


def result(request):
    if request.method == "GET":
        return redirect("jurimetria:index")

    vara, tipo, busca = get_post_query_input(request)
    query = SearchQuery(unidecode(busca), config="portuguese")

    sents = Sentenca.objects.filter(vara=vara, search_vector=query)

    if len(sents) == 0:
        context = {"erro": "Não há sentenças com os filtros selecionados."}
        return render(request, "jurimetria/index.html", context)

    sentencas = sents.filter(tipo=tipo)
    sents_rank = sentencas.annotate(rank=SearchRank(F("search_vector"), query)).order_by("-rank")[:10]

    categorias = sents.order_by("tipo").values("tipo").annotate(count=Count("tipo"))
    cat_counts = query_counts(categorias)
    query_count = len(sents)

    query_qtd, vals_pcts = make_output_tuple(cat_counts, busca, query_count, vara)

    context = {"sentencas": sents_rank, "query": query_qtd, "vals": vals_pcts, "tipo": coloca_acento(tipo)}

    return render(request, "jurimetria/result.html", context)


def detail(request, sentenca_id):
    sentenca = get_object_or_404(Sentenca, pk=sentenca_id)
    sentenca.numero = formata_numero_cnj(sentenca.numero)
    sentenca.vara = VARAS_NOMES[sentenca.vara]
    sentenca.tipo = coloca_acento(sentenca.tipo)
    context = {"sentenca": sentenca}
    return render(request, "jurimetria/detail.html", context)

jurimetria/templates/jurimetria/barra-busca.html
<div class="result-search">
  <form action="{% url 'jurimetria:result' %}" method="post">{% csrf_token %}
    <div class="result-search-query">
      <input type="text" name="query" id="query" placeholder="Busca">
      <button type="submit"><i class="fas fa-search"></i></button>
    </div>
    <div class="result-search-filtros">
      {% include 'jurimetria/select-vara.html' %}
      {% include 'jurimetria/select-tipo.html' %}
    </div>
  </form>
</div>

jurimetria/templates/jurimetria/detail.html
{% extends 'jurimetria/layout.html' %}

<!-- css -->
{% block css %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'jurimetria/detail.css' %}">
{% endblock %}


<!-- conteudo -->
{% block content %}

  <div class="detail-content">

    <!-- barra busca -->
    {% include 'jurimetria/barra-busca.html' %}

    <div class="detail-cabecalho">
      <h1>Processo nº: {{ sentenca.numero }}</h1>
      <h2>{{ sentenca.vara }}</h2>
      <h3>Categoria: {{ sentenca.tipo }}</h3>
    </div>

    <div class="detail-sentenca">
      <pre>{{ sentenca.texto }}</pre>
    </div>

  </div>

{% endblock %}

jurimetria/templates/jurimetria/index.html
{% extends 'jurimetria/layout.html' %}

<!-- css -->
{% block css %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'jurimetria/index.css' %}">
{% endblock %}


<!-- conteudo -->
{% block content %}

  <div class="index-content">
    <!-- form busca -->
    <div class="index-search">
      <h1>Jurimetria</h1>
      <form action="{% url 'jurimetria:result' %}" method="post">{% csrf_token %}
        <input type="text" name="query" id="query" placeholder="Busca">
        {% include 'jurimetria/select-vara.html' %}
        {% include 'jurimetria/select-tipo.html' %}
        <button type="submit">Pesquisar</button>
      </form>
    </div>
  </div>

  {% if erro %}
    <p class="mensagem-erro">{{ erro }}</p>
  {% endif %}

  <a href="https://tjfacil.wordpress.com/2020/07/20/classificando-sentencas-criminais-utilizando-aprendizado-de-maquina/" target="_blank">
    <h2>Como funciona</h2>
  </a>

{% endblock %}

jurimetria/templates/jurimetria/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:300,400,700|Merriweather:400,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500;900&family=Ubuntu:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'master/master.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'jurimetria/style.css' %}">
  {% block css %} <!-- css for each page --> {% endblock %}
  <script type="text/javascript" src="{% static 'jurimetria/script.js' %}"></script>
  <script src="https://kit.fontawesome.com/1625b5a72a.js" crossorigin="anonymous"></script>
  <title>Jurimetria</title>
</head>
<body>

  <a href="#" id="link-menu">Menu</a>
  {% include 'menu/menu.html' %}

  {% block content %}{% endblock %}
</body>

jurimetria/templates/jurimetria/result.html
{% extends 'jurimetria/layout.html' %}

<!-- css -->
{% block css %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'jurimetria/result.css' %}">
{% endblock %}


<!-- conteudo -->
{% block content %}
  <div class="result-content">

    <!-- barra busca -->
    {% include 'jurimetria/barra-busca.html' %}


    <div class="resultados">
      <!-- total de hits e porcentagens -->
      <div class="estatisticas">
        <h2>{{ query }}</h2>
        <h3><pre>{{ vals }}</pre></h3>
      </div>

      <!-- cards sentenças -->
      {% if sentencas %}
      <div class="sentencas">
        <h3>Sentenças {{ tipo }}:</h3>
        <ul>
          {% for sentenca in sentencas %}
          <a href="{% url 'jurimetria:detail' sentenca.id %}">
            <div class="cada-sentenca">
              <li>{{ sentenca.decoded|slice:"750:1300" }}</li>
            </div>
          </a>
          {% endfor %}
        </ul>
      </div>
      {% else %}
        <p>Não foi encontrada nenhuma sentença com o tipo pesquisado.</p>
      {% endif %}

    </div>

  </div>
{% endblock %}

jurimetria/templates/jurimetria/select-tipo.html
<select class="selects" name="select-tipo">
  <option value="absolutorias">Absolutória</option>
  <option value="condenatorias">Condenatória</option>
  <option value="neutras">Neutra</option>
</select>

jurimetria/templates/jurimetria/select-vara.html
<select class="selects" name="select-vara">
  <option value="1">1ª Vara Criminal BH</option>
  <option value="3">3ª Vara Criminal BH</option>
  <option value="4">4ª Vara Criminal BH</option>
  <option value="5">5ª Vara Criminal BH</option>
  <option value="7">7ª Vara Criminal BH</option>
  <option value="8">8ª Vara Criminal BH</option>
  <option value="9">9ª Vara Criminal BH</option>
  <option value="10">10ª Vara Criminal BH</option>
  <option value="12">12ª Vara Criminal BH</option>
  <!-- <option value="t1">1ª Vara de Tóxicos BH</option>
  <option value="t2">2ª Vara de Tóxicos BH</option>
  <option value="t3">3ª Vara de Tóxicos BH</option>
  <option value="b1">1ª Vara Criminal Betim</option>
  <option value="c2">2ª Vara Criminal Contagem</option>
  <option value="c3">3ª Vara Criminal Contagem</option>
  <option value="u1">1ª Vara Criminal Uberlândia</option>
  <option value="u2">2ª Vara Criminal Uberlândia</option>
  <option value="j4">4ª Vara Criminal Juiz de Fora</option>
  <option value="m1">1ª Vara Criminal Montes Claros</option> -->
</select>